const themes={clean:{label:'클린 민트'},blue:{label:'소프트 블루'},violet:{label:'소프트 바이올렛'},coral:{label:'클린 코랄'},mono:{label:'밝은 모노'},lime:{label:'라임 편집형'}};
const labels={call:'전화',sms:'문자',email:'이메일',social:'카카오톡',website:'웹사이트',share:'QR · NFC'},CORE_REQUEST_ID='electronic-card-product-v1';
const state={view:'profile',theme:'clean',photo:'/electronic-card-product/portrait-cutout.png',scale:100,position:28,profile:{},careers:[],actionOrder:Object.keys(labels)};
const views=[...document.querySelectorAll('[data-view]')],toast=document.querySelector('.toast'),form=document.querySelector('#profile-form');
const esc=(v='')=>String(v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])),attr=(v='')=>esc(v).replace(/"/g,'&quot;');
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function setText(s,v){const n=document.querySelector(s);if(n)n.textContent=v||''}function safePhone(v=''){return v.replace(/[^0-9+]/g,'')}
function setView(v){state.view=v;views.forEach(n=>n.classList.toggle('is-active',n.dataset.view===v));document.querySelectorAll('[data-nav]').forEach(n=>n.classList.toggle('selected',n.dataset.nav===v));document.querySelector('.back-button').hidden=v==='profile';document.querySelector('.topbar [data-action="edit"]').hidden=v==='edit'||v==='complete';setText('#page-title',{profile:state.profile.name||'전자명함',about:'소개 · 경력',share:'QR · NFC 공유',edit:'프로필 편집',complete:'제작 완료'}[v]);scrollTo({top:0,behavior:'auto'})}
function renderCareers(){const timeline=document.querySelector('#career-timeline');timeline.innerHTML=state.careers.map(c=>`<li><b>${esc(c.period)}</b><span>${esc(c.title)}<br>${esc(c.description)}</span></li>`).join('');timeline.hidden=state.careers.length===0}
function applyProfile(){const p=state.profile;[['#profile-name',p.name],['.role',p.role],['.intro',p.intro],['#profile-eyebrow',p.eyebrow],['#profile-services',p.services],['#about-title',p.name],['#about-role',p.role],['#about-eyebrow',p.eyebrow],['#about-body',p.about_body],['#nfc-message',p.nfc_message],['#complete-name',p.name],['#complete-role',p.role]].forEach(x=>setText(...x));const consultation=document.querySelector('#consultation-link');consultation.textContent=p.consultation_label;consultation.href=p.consultation_url||'#';consultation.hidden=!p.consultation_label||!p.consultation_url;document.title=`${p.name||'전자명함'} ${p.role||''} · 전자명함`;document.querySelectorAll('[data-portrait-frame]').forEach(f=>f.dataset.initials=(p.name||'?').trim().slice(0,1));document.querySelectorAll('a[data-action-id="call"]').forEach(a=>{a.href=`tel:${safePhone(p.phone)}`;a.hidden=!p.phone});document.querySelectorAll('a[data-action-id="sms"]').forEach(a=>{a.href=`sms:${safePhone(p.phone)}`;a.hidden=!p.phone});document.querySelectorAll('a[data-action-id="email"]').forEach(a=>{a.href=`mailto:${p.email||''}`;a.hidden=!p.email});const social=document.querySelector('a[data-action-id="social"]'),website=document.querySelector('a[data-action-id="website"]');social.href=p.social_url||'#';social.textContent=p.social_label||'SNS';social.hidden=!p.social_url;website.href=p.website_url||'#';website.textContent=p.website_label||'웹사이트';website.hidden=!p.website_url;[['.intro',p.intro],['#profile-eyebrow',p.eyebrow],['#profile-services',p.services],['#about-eyebrow',p.eyebrow],['#about-body',p.about_body],['#nfc-message',p.nfc_message]].forEach(([selector,value])=>{document.querySelector(selector).hidden=!value});renderCareers()}
function fillEditor(){Object.entries(state.profile).forEach(([k,v])=>{const n=form.elements.namedItem(k);if(n)n.value=v});renderCareers();renderActions()}
function fillTabEditors(){const about=document.querySelector('#inline-about-editor'),share=document.querySelector('#inline-share-editor');about.elements.eyebrow.value=state.profile.eyebrow||'';about.elements.about_body.value=state.profile.about_body||'';share.elements.nfc_message.value=state.profile.nfc_message||''}
function renderActions(){const grid=document.querySelector('#action-grid'),existing={};[...grid.children].forEach(n=>existing[n.dataset.actionId]=n);state.actionOrder.forEach(id=>grid.append(existing[id]));document.querySelector('#action-order').innerHTML=state.actionOrder.map((id,i)=>`<li data-order-id="${id}" draggable="true"><span class="drag-handle" aria-hidden="true">⠿</span><span>${i+1} · ${esc(id==='social'?(state.profile.social_label||labels[id]):id==='website'?(state.profile.website_label||labels[id]):labels[id])}</span><button type="button" data-move="up" aria-label="${labels[id]} 위로 이동" ${i===0?'disabled':''}>↑</button><button type="button" data-move="down" aria-label="${labels[id]} 아래로 이동" ${i===state.actionOrder.length-1?'disabled':''}>↓</button></li>`).join('')}
function applyPhoto(){document.querySelectorAll('#profile-photo,#editor-photo,[data-profile-photo]').forEach(img=>{const f=img.closest('[data-portrait-frame]');img.hidden=!state.photo;f?.classList.toggle('is-placeholder',!state.photo);if(state.photo){img.src=state.photo;img.style.transform=`scale(${state.scale/100})`;img.style.objectPosition=`center ${state.position}%`}})}
function clearCustom(){['--accent','--accent-ink','--highlight','--hero-shape','--panel','--panel-card','--panel-line','--completion','--note'].forEach(p=>document.documentElement.style.removeProperty(p))}function hexRgb(h){h=h.replace('#','');return[0,2,4].map(i=>parseInt(h.slice(i,i+2),16))}function mix(a,b,w){const x=hexRgb(a),y=hexRgb(b);return'#'+x.map((v,i)=>Math.round(v*(1-w)+y[i]*w).toString(16).padStart(2,'0')).join('')}function ink(c){const [r,g,b]=hexRgb(c);return .2126*r+.7152*g+.0722*b>148?'#10201d':'#fff'}
function selectTheme(id,text){document.querySelectorAll('[data-theme-option]').forEach(b=>{const s=b.dataset.themeOption===id;b.classList.toggle('selected',s);b.setAttribute('aria-pressed',s)});setText('#theme-current',text)}function applyTheme(id){clearCustom();state.theme=id;document.documentElement.dataset.theme=id;selectTheme(id,`현재 적용: ${themes[id].label}`)}function applyCustom(c){const r=document.documentElement;state.theme='custom';r.dataset.theme='custom';[['--accent',c],['--accent-ink',ink(c)],['--highlight',mix(c,'#000000',.22)],['--hero-shape',mix(c,'#ffffff',.84)],['--panel',mix(c,'#081210',.72)],['--panel-card',mix(c,'#14221f',.62)],['--panel-line',mix(c,'#ffffff',.56)],['--completion',mix(c,'#081210',.72)],['--note',mix(c,'#000000',.38)]].forEach(([p,v])=>r.style.setProperty(p,v));document.querySelector('#custom-theme-color').value=c;selectTheme('custom',`현재 적용: 직접 만든 테마 · ${c}`)}
async function coreAction(action,detail={}){const r=await fetch('/api/electronic-card/ui-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:CORE_REQUEST_ID,action,...detail})}),p=await r.json();if(!r.ok)throw new Error(p.error||'Core 저장 실패');return p.state}function acceptCore(c){state.profile=c.profile;state.careers=c.careers;state.actionOrder=c.action_order;c.theme.preset==='custom'?applyCustom(c.theme.custom_color):applyTheme(c.theme.preset);applyProfile();fillEditor();fillTabEditors()}
async function loadCore(){try{const r=await fetch(`/api/electronic-card/ui-state?request_id=${CORE_REQUEST_ID}`,{cache:'no-store'}),c=await r.json();if(!r.ok)throw new Error(c.error);acceptCore(c)}catch(e){console.error(e);showToast('Core 상태를 불러오지 못했습니다')}}
async function saveContent(){const profile={...state.profile,...Object.fromEntries(new FormData(form))};if(!profile.name.trim()||!profile.role.trim())throw new Error('이름과 직책은 비워둘 수 없습니다');acceptCore(await coreAction('content.update',{profile,careers:state.careers,action_order:state.actionOrder}));setView('complete');showToast('프로필 정보를 Core에 저장했습니다')}
function setCareerEditor(open){const panel=document.querySelector('#inline-career-editor'),button=document.querySelector('[data-action="toggle-career-edit"]');panel.hidden=!open;button.setAttribute('aria-expanded',String(open));button.textContent=open?'입력 닫기':'경력 추가';if(open)document.querySelector('#career-add-form').reset()}
function careerPeriod(start,end,current){const format=value=>value.replace('-', '.');return `${format(start)} ~ ${current?'현재':format(end)}`}
async function addCareer(){const form=document.querySelector('#career-add-form'),values=Object.fromEntries(new FormData(form)),current=form.elements.current.checked;if(!values.start||!values.title.trim()||!values.description.trim())throw new Error('시작 월·기관/직책·담당 업무를 입력해주세요');if(!current&&!values.end)throw new Error('종료 월을 선택하거나 현재 근무 중을 체크해주세요');if(!current&&values.start>values.end)throw new Error('종료 월은 시작 월보다 빠를 수 없습니다');const career={period:careerPeriod(values.start,values.end,current),title:values.title.trim(),description:values.description.trim()};acceptCore(await coreAction('career.add',{career}));setCareerEditor(false);showToast('경력을 최신순으로 자동 배치했습니다')}
function setTabEditor(kind,open){const panel=document.querySelector(`#inline-${kind}-editor`),button=document.querySelector(`[data-action="toggle-${kind}-edit"]`);panel.hidden=!open;button.setAttribute('aria-expanded',String(open));button.textContent=open?'편집 닫기':kind==='about'?'소개 편집':'안내 편집';if(open)fillTabEditors()}
async function saveTabFields(kind){const editor=document.querySelector(`#inline-${kind}-editor`),profile={...state.profile,...Object.fromEntries(new FormData(editor))};acceptCore(await coreAction('content.update',{profile,careers:state.careers,action_order:state.actionOrder}));setTabEditor(kind,false);showToast(kind==='about'?'소개를 Core에 저장했습니다':'공유 안내를 Core에 저장했습니다')}
function regenerateQr(){const status=document.querySelector('#qr-regenerate-status');if(['127.0.0.1','localhost'].includes(location.hostname)){status.textContent='현재는 시험 주소입니다. 공개 주소가 확정되면 해당 주소로 QR을 다시 생성할 수 있습니다.';showToast('공개 주소 확정 후 QR 재생성이 가능합니다');return}status.textContent='Core QR 생성기가 아직 연결되지 않아 재생성을 중단했습니다.';showToast('QR 생성기 연결이 필요합니다')}
async function saveContact(){const p=state.profile,v=`BEGIN:VCARD\nVERSION:3.0\nFN:${p.name}\nORG:${p.organization}\nTITLE:${p.role}\nTEL:${p.phone}\nEMAIL:${p.email}\nEND:VCARD`,u=URL.createObjectURL(new Blob([v],{type:'text/vcard'})),a=document.createElement('a');a.href=u;a.download='electronic-card.vcf';a.click();URL.revokeObjectURL(u);setView('complete')}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-action]')?.dataset.action;try{if(a==='back')setView('profile');if(a==='edit'){fillEditor();setView('edit')}if(a==='share')setView('share');if(a==='go-profile')setView('profile');if(a==='save-contact')await saveContact();if(a==='native-share'){if(navigator.share)await navigator.share({title:document.title,text:`${state.profile.name} 전자명함`,url:location.href});else await navigator.clipboard?.writeText(location.href)}if(a==='finish-edit')await saveContent();if(a==='toggle-about-edit')setTabEditor('about',document.querySelector('#inline-about-editor').hidden);if(a==='cancel-about-edit'){fillTabEditors();setTabEditor('about',false)}if(a==='save-about')await saveTabFields('about');if(a==='toggle-share-edit')setTabEditor('share',document.querySelector('#inline-share-editor').hidden);if(a==='cancel-share-edit'){fillTabEditors();setTabEditor('share',false)}if(a==='save-share')await saveTabFields('share');if(a==='regenerate-qr')regenerateQr();if(a==='toggle-career-edit')setCareerEditor(document.querySelector('#inline-career-editor').hidden);if(a==='cancel-career-edit')setCareerEditor(false);if(a==='add-career')await addCareer();if(a==='reset-photo'){state.photo=null;applyPhoto()}if(a==='restore-theme'){acceptCore(await coreAction('theme.restore'));showToast('이전 테마를 복원했습니다')}if(a==='restore-content'){acceptCore(await coreAction('content.restore'));showToast('이전 저장 내용을 복원했습니다')}}catch(err){showToast(err.message)}});
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.nav==='edit')fillEditor();setView(b.dataset.nav)}));document.querySelector('.theme-options').addEventListener('click',async e=>{const b=e.target.closest('[data-theme-option]');if(b)try{acceptCore(await coreAction('theme.select',{preset:b.dataset.themeOption}))}catch(err){showToast(err.message)}});document.querySelector('#custom-theme-color').addEventListener('change',async e=>{try{acceptCore(await coreAction('theme.custom.set',{color:e.target.value}))}catch(err){showToast(err.message)}});
const order=document.querySelector('#action-order');order.addEventListener('click',e=>{const b=e.target.closest('[data-move]');if(!b)return;const i=state.actionOrder.indexOf(b.closest('[data-order-id]').dataset.orderId),t=b.dataset.move==='up'?i-1:i+1;if(t>=0&&t<state.actionOrder.length)[state.actionOrder[i],state.actionOrder[t]]=[state.actionOrder[t],state.actionOrder[i]];renderActions()});order.addEventListener('dragstart',e=>{const row=e.target.closest('[data-order-id]');if(row)e.dataTransfer.setData('text/plain',row.dataset.orderId)});order.addEventListener('dragover',e=>e.preventDefault());order.addEventListener('drop',e=>{e.preventDefault();const s=e.dataTransfer.getData('text/plain'),t=e.target.closest('[data-order-id]')?.dataset.orderId;if(!s||!t||s===t)return;const from=state.actionOrder.indexOf(s),to=state.actionOrder.indexOf(t);state.actionOrder.splice(to,0,state.actionOrder.splice(from,1)[0]);renderActions()});
document.querySelector('#photo-scale').addEventListener('input',e=>{state.scale=+e.target.value;applyPhoto()});document.querySelector('#photo-position').addEventListener('input',e=>{state.position=+e.target.value;applyPhoto()});document.querySelector('#photo-input').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f?.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{state.photo=r.result;applyPhoto()};r.readAsDataURL(f)});
applyPhoto();applyTheme('clean');setView(new URLSearchParams(location.search).get('view')||'profile');loadCore();
